### PR TITLE
update to qgis3

### PR DESCRIPTION
**Pull request by enzococca**

### CODE REVIEW

**Comment by enzococca** [comment]
Hi, 
I make the porting to qgis3 , check it is work well for you

**Comment by borysiasty** [comment]
Hi @enzococca, honestly speaking I don't plan to keep the table manager alive... Now we have a native Processing algorithm (Refactor Fields) so I'd rather focus all efforts on its development. The biggest problem with Table Manager is it's dedicated for Shapefiles, while I really wish people migrate to GeoPackage (or other modern formats). If you find the Table Manager useful anyway, would you like to take over the maintenance?

**Comment by enzococca** [comment]
Hi,
Of course. I think this plugin is very useful also you use only the
shapefile.

Best
Enzo

Il Dom 14 Apr 2019, 21:36 Borys Jurgiel <notifications@github.com> ha
scritto:

**Comment by borysiasty** [comment]
Sorry I'm not sure if I understand you: "of course" you want to take over the maintenance or "of course" you agree the Refactor Fields is a better way to go? :) 

In the former case, you can just update urls in the metadata.txt, add yourself to the authors and try to upload the plugin to the repository (Paolo will manually update the maintainer if necessary).

**Pull request closed without merging**
